[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "django-mathfilters>=1.0.0",
    "django>=5.1.7",
    "pillow>=11.1.0",
    "openpyxl>=3.1.5",
    "xhtml2pdf>=0.2.17",
    "pytz>=2025.2",
]
