# Generated by Django 5.1.4 on 2025-04-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'figma done'), ('Other_Company', 'Other_Company'), ('Cheque', 'Cheque'), ('Paypal', 'Paypal')], default='upcoming', max_length=20),
        ),
    ]
