# Generated by Django 5.1.4 on 2025-03-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('started', 'started'), ('figma_completed', 'figma done'), ('frontend_completed', 'frontend completed'), ('backend_completed', 'backend completed'), ('completed', 'completed')], default='upcoming', max_length=20),
        ),
    ]
